name: 'CI'

on: pull_request

jobs:
  sleep-for-CI:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 15

  fast-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"

  slow-check:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 20 && echo "done"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - run: npm run all

  test-regex-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          check-run-regex: "^sleep-for-CI$"

  test-required-checks-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          required-check-runs: |
            fast-check
            slow-check
          timeout-seconds: 120
