name: 'CI'

on: pull_request

jobs:
  sleep-for-CI:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 15

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          check-run-regex: "^sleep-for-CI$"
